import Link from "next/link";
import { PageHeader } from "@/components/community-shell";
import { KpiCard, ReportCard, type ReportSummary } from "@/components/record-cards";
import { createClient } from "@/lib/supabase/server";

type Kpis={reports_count:number|null;issues_count:number|null;active_issues_count:number|null;new_issues_30d_count:number|null;resolved_issues_count:number|null;partially_resolved_count:number|null;no_response_count:number|null;median_first_known_hours:number|null;median_first_official_hours:number|null;median_resolution_hours:number|null;commitments_on_time:number|null;commitments_late:number|null;commitments_active:number|null;commitments_overdue:number|null;declared_recurrence_count:number|null;divergent_status_count:number|null;information_without_response_count:number|null;affected_people_count:number|null;affected_unit_count:number|null;affected_block_count:number|null;minimum_group_size:number};
const metricLabels:Record<string,string>={active:"Problemas ativos",resolved:"Problemas resolvidos",no_response:"Sem retorno registrado",recurrence:"Recorrência declarada",divergent:"Status divergente",information_without_response:"Pedidos de informação sem resposta"};
function count(value:number|null|undefined){return value==null?"<3":value}
function duration(hours:number|null|undefined){if(hours==null)return"<3 casos";return hours<48?`${Math.round(hours)} h`:`${Math.round(hours/24)} dias`}

export default async function IndicatorsPage({searchParams}:{searchParams:Promise<{metric?:string;origin?:string}>}){
  const{metric="",origin="native"}=await searchParams;const safeOrigin=["native","historical","all"].includes(origin)?origin:"native";const supabase=await createClient();
  let agingQuery=supabase.from("report_aging").select("aging_bucket,source_origin");if(safeOrigin!=="all")agingQuery=agingQuery.eq("source_origin",safeOrigin);
  const[{data:kpiData},{data:aging},{data:drill}]=await Promise.all([supabase.rpc("community_kpi_summary",{p_origin:safeOrigin}),agingQuery,metric?supabase.rpc("kpi_drilldown",{p_metric:metric,p_origin:safeOrigin,p_limit:50}):Promise.resolve({data:null})]);
  const kpi=(kpiData??{})as Partial<Kpis>;const buckets=(aging??[]).reduce<Record<string,number>>((totals,row)=>(totals[row.aging_bucket]=(totals[row.aging_bucket]??0)+1,totals),{});const card=(metricKey:string,label:string,value:string|number,note:string)=><Link href={`/indicadores?metric=${metricKey}&origin=${safeOrigin}`}><KpiCard label={label} value={value} note={`${note} · abrir registros`}/></Link>;
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><PageHeader eyebrow="Leitura responsável" title="Indicadores comunitários" description="Desempenho atual usa dados nativos por padrão. Ausência de retorno conhecido não prova ausência de providência."/><nav className="mt-5 flex gap-2" aria-label="Origem dos indicadores">{[["native","Nativos"],["historical","Históricos"],["all","Todos"]].map(([value,label])=><Link key={value} href={`/indicadores?origin=${value}`} aria-current={safeOrigin===value?"page":undefined} className={`rounded-lg px-3 py-2 font-semibold ${safeOrigin===value?"bg-forest text-white":"border bg-white"}`}>{label}</Link>)}</nav>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{card("all","Relatos",count(kpi.reports_count),"Registros, não pessoas")}{card("active","Problemas ativos",count(kpi.active_issues_count),"Issues coletivas")}<KpiCard label="Novos problemas (30d)" value={count(kpi.new_issues_30d_count)} note="Issues criadas"/>{card("resolved","Problemas resolvidos",count(kpi.resolved_issues_count),"Estado coletivo derivado")}<KpiCard label="Parcialmente resolvidos" value={count(kpi.partially_resolved_count)} note="Estado do relato"/>{card("no_response","Sem retorno registrado",count(kpi.no_response_count),"Texto neutro")}{card("recurrence","Recorrência declarada",count(kpi.declared_recurrence_count),"Separada de persistência")}{card("divergent","Status divergente",count(kpi.divergent_status_count),"Conclusão oficial × morador")}{card("information_without_response","Pedidos de informação sem resposta",count(kpi.information_without_response_count),"Tipo filtrado")}<KpiCard label="Compromissos no prazo" value={count(kpi.commitments_on_time)} note="Cumpridos no prazo"/><KpiCard label="Compromissos com atraso" value={count(kpi.commitments_late)} note="Cumpridos após o prazo"/><KpiCard label="Compromissos vigentes" value={count(kpi.commitments_active)} note="Prazo atual"/><KpiCard label="Compromissos vencidos" value={count(kpi.commitments_overdue)} note="Prazo atual vencido"/><KpiCard label="Pessoas afetadas" value={count(kpi.affected_people_count)} note="Pessoas distintas"/><KpiCard label="Unidades afetadas" value={count(kpi.affected_unit_count)} note="Unidades distintas"/><KpiCard label="Blocos afetados" value={count(kpi.affected_block_count)} note="Blocos distintos"/></section>
    <section className="mt-9 grid gap-4 sm:grid-cols-3"><KpiCard label="Mediana até primeiro retorno conhecido" value={duration(kpi.median_first_known_hours)} note="Não equivale a resposta oficial"/><KpiCard label="Mediana até primeira resposta oficial" value={duration(kpi.median_first_official_hours)} note="Publicada por representação válida"/><KpiCard label="Mediana até resolução" value={duration(kpi.median_resolution_hours)} note={`Origem: ${safeOrigin}`}/></section>
    <section className="mt-9 rounded-2xl bg-white p-6"><h2 className="text-xl font-bold">Envelhecimento dos relatos</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{Object.entries(buckets).map(([label,value])=><div key={label} className="rounded-xl bg-sand p-4"><b className="text-2xl">{value<3?"<3":value}</b><p className="text-sm">{label}</p></div>)}</div><p className="mt-5 text-sm text-[#666861]">Grupos abaixo de {kpi.minimum_group_size??3} são suprimidos para reduzir reidentificação.</p></section>
    {metric&&<section className="mt-9"><h2 className="text-2xl font-bold">Registros: {metricLabels[metric]??"Indicador"}</h2><div className="mt-4 grid gap-4">{(drill as ReportSummary[]|null)?.map(report=><ReportCard key={report.id} report={report}/>)}</div></section>}
  </main>;
}
