// The OpenNext worker is generated by `opennextjs-cloudflare build`.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- generated module is absent before the Cloudflare build
// @ts-ignore generated module is intentionally absent before the Cloudflare build
import handler from "./.open-next/worker.js";

type LastroCloudflareEnv = {
  CRON_SECRET: string;
};

type CloudflareScheduledController = {
  cron: string;
};

type CloudflareExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
};

const scheduledRoutes: Record<string, string> = {
  "0 3 * * *": "/api/cron/commitments",
  "0 12 * * *": "/api/cron/notifications",
};

const worker = {
  fetch: handler.fetch,

  async scheduled(
    event: CloudflareScheduledController,
    env: LastroCloudflareEnv,
    ctx: CloudflareExecutionContext,
  ) {
    const pathname = scheduledRoutes[event.cron];
    if (!pathname) return;

    const response = handler.fetch(
      new Request(`https://lastro.internal${pathname}`, {
        method: "POST",
        headers: { authorization: `Bearer ${env.CRON_SECRET}` },
      }),
      env,
      ctx,
    );

    ctx.waitUntil(Promise.resolve(response));
  },
};

export default worker;
