import Link from "next/link";
import { PageHeader } from "@/components/community-shell";
import { createClient } from "@/lib/supabase/server";
import { createReportAction } from "./actions";

const input = "mt-1 w-full rounded-xl border border-[#bcb5ad] bg-white px-3 py-2.5";
export default async function RegisterPage({ searchParams }: { searchParams: Promise<{ issue?: string }> }) {
  const { issue = "" } = await searchParams; const supabase = await createClient();
  const [{ data: types }, { data: categories }, { data: locations }] = await Promise.all([
    supabase.from("report_types").select("slug,name").is("archived_at", null).order("sort_order"),
    supabase.from("categories").select("slug,name,subcategories(slug,name,sort_order)").is("archived_at", null).order("sort_order"),
    supabase.from("locations").select("id,label").is("archived_at", null).order("sort_order"),
  ]);
  return <main className="mx-auto max-w-4xl px-4 py-8 sm:px-6"><PageHeader eyebrow="Novo registro" title="Registrar um relato" description="Descreva o que ocorreu. O conteúdo original fica preservado e recebe protocolo único."/>
    <div className="mt-5 rounded-xl border-l-4 border-info bg-[#e8f3f7] p-4 text-sm"><b>Antes de continuar:</b> <Link href="/problemas" className="underline">pesquise problemas semelhantes</Link>. Em emergência ou risco imediato, acione os serviços públicos adequados; o LASTRO não é canal emergencial.</div>
    <form action={createReportAction} className="mt-7 space-y-7"><input type="hidden" name="issue_id" value={issue}/>
      <fieldset className="rounded-2xl border border-[#ded8d1] bg-white p-5"><legend className="px-2 text-lg font-bold">1. Natureza e classificação</legend><div className="grid gap-4 sm:grid-cols-2">
        <label>Tipo de registro<select required name="type" className={input}><option value="">Selecione</option>{types?.map(t=><option key={t.slug} value={t.slug}>{t.name}</option>)}</select></label>
        <label>Categoria<select required name="category" className={input}><option value="">Selecione</option>{categories?.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select></label>
        <label>Subcategoria<select name="subcategory" className={input}><option value="">Não informada</option>{categories?.map(c=><optgroup key={c.slug} label={c.name}>{c.subcategories?.sort((a,b)=>a.sort_order-b.sort_order).map(s=><option key={`${c.slug}-${s.slug}`} value={s.slug}>{s.name}</option>)}</optgroup>)}</select></label>
        <label>Abrangência<select required name="scope" className={input}><option value="common_area">Área comum</option><option value="unit">Minha unidade</option><option value="multiple_units">Algumas unidades</option><option value="block">Meu bloco</option><option value="multiple_blocks">Mais de um bloco</option><option value="whole_condo">Todo o condomínio</option><option value="unknown">Não sei determinar</option></select></label>
      </div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label>Se escolheu “Outros”, sugira a categoria<input name="suggested_category_text" className={input}/></label><label>Sugestão de subcategoria<input name="suggested_subcategory_text" className={input}/></label></div></fieldset>
      <fieldset className="rounded-2xl border border-[#ded8d1] bg-white p-5"><legend className="px-2 text-lg font-bold">2. Localização</legend><p className="mb-3 text-sm text-[#686a63]">Selecione todos os locais aplicáveis. A lista é administrável e não substitui a abrangência.</p><div className="grid gap-2 sm:grid-cols-2">{locations?.map(location=><label key={location.id} className="rounded-lg border p-3"><input type="checkbox" name="location_ids" value={location.id}/> {location.label}</label>)}</div></fieldset>
      <fieldset className="rounded-2xl border border-[#ded8d1] bg-white p-5"><legend className="px-2 text-lg font-bold">3. O que aconteceu</legend><label>Título objetivo<input required minLength={8} maxLength={180} name="title" className={input}/></label><label className="mt-4 block">Descrição com fatos e contexto<textarea required minLength={20} maxLength={10000} rows={7} name="description" className={input}/></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label>Quando ocorreu<input type="datetime-local" name="occurred_at" className={input}/></label><label>Urgência<select required name="urgency" className={input}><option value="routine">Rotina</option><option value="attention">Atenção</option><option value="urgent">Urgente</option><option value="possible_immediate_risk">Possível risco imediato</option></select></label></div><div className="mt-4 flex flex-wrap gap-5"><label><input type="checkbox" name="is_ongoing"/> Ainda está acontecendo</label><label><input type="checkbox" name="declared_recurrence"/> Já ocorreu antes</label><label><input type="checkbox" name="previously_communicated"/> Já foi comunicado</label></div><label className="mt-4 block">Possível responsável ou canal já procurado<input name="expected_responsible_party" className={input}/></label></fieldset>
      <fieldset className="rounded-2xl border border-[#ded8d1] bg-white p-5"><legend className="px-2 text-lg font-bold">4. Proteção e publicação</legend><div className="grid gap-4 sm:grid-cols-3"><label>Identidade<select name="identity_mode" className={input}><option value="identified">Exibir nome</option><option value="protected">Identidade protegida</option><option value="protected_with_block">Protegida, com bloco</option></select></label><label>Visibilidade<select name="visibility" className={input}><option value="community">Comunidade</option><option value="restricted">Restrita</option><option value="author_and_moderators">Autor e moderação</option></select></label><label>Sensibilidade<select name="sensitivity" className={input}><option value="normal">Normal</option><option value="contains_personal_data">Contém dados pessoais</option><option value="identified_third_party">Envolve terceiro identificado</option><option value="child_or_adolescent">Envolve criança/adolescente</option><option value="possible_personal_risk">Possível risco pessoal</option><option value="sensitive_allegation">Denúncia sensível</option></select></label></div><label className="mt-4 flex gap-2"><input type="checkbox" name="identifies_third_party"/> O texto identifica ou acusa uma pessoa ou organização</label><p className="mt-3 rounded-lg bg-[#fff3dc] p-3 text-sm">Conteúdo de maior sensibilidade entra automaticamente para autor e moderação, mesmo que “Comunidade” tenha sido selecionado.</p></fieldset>
      <label className="flex gap-3 rounded-xl bg-forest-soft p-4"><input required type="checkbox" name="good_faith"/><span>Declaro que registro este relato de boa-fé, distinguindo fatos de percepções e sem usar a plataforma para assédio ou exposição indevida.</span></label>
      <div className="flex justify-end"><button className="rounded-xl bg-brick px-6 py-3 font-bold text-white">Registrar e gerar protocolo</button></div>
    </form></main>;
}
