import{NextRequest,NextResponse}from"next/server";
import{getEmailProvider}from"@/lib/email";
import{correlationId,logEvent}from"@/lib/observability";
import{createAdminClient}from"@/lib/supabase/admin";
type Claimed={notification_id:string;email:string;subject:string;body:string;target_path:string|null};
export async function POST(request:NextRequest){const requestId=correlationId(request);const startedAt=new Date().toISOString();const route="/api/cron/notifications";const respond=(body:Record<string,unknown>,status=200)=>NextResponse.json(body,{status,headers:{"x-request-id":requestId}});const expected=process.env.CRON_SECRET;if(!expected||request.headers.get("authorization")!==`Bearer ${expected}`){logEvent("warn",{correlationId:requestId,route,operation:"authorize",errorCode:"unauthorized"});return respond({error:"unauthorized"},401)}const s=createAdminClient();if(!s)return respond({error:"server_configuration_missing"},503);const{data,error}=await s.rpc("claim_notification_emails",{p_limit:25});if(error){logEvent("error",{correlationId:requestId,route,operation:"claim",errorCode:"email_claim_failed"});await Promise.all([s.rpc("record_job_result",{p_job_name:"notification_email",p_status:"failed",p_attempted:0,p_succeeded:0,p_error_code:"email_claim_failed",p_correlation_id:requestId,p_started_at:startedAt}),s.rpc("record_operational_failure",{p_correlation_id:requestId,p_route:route,p_operation:"claim",p_error_code:"email_claim_failed",p_safe_metadata:{}})]);return respond({error:"claim_failed"},500)}const provider=getEmailProvider();let sent=0;let failed=0;for(const item of(data??[])as Claimed[]){let success=false;try{const base=process.env.NEXT_PUBLIC_APP_URL??"";await provider.send({to:item.email,subject:`LASTRO · ${item.subject}`,text:`${item.body}${item.target_path?`\n\n${base}${item.target_path}`:""}`});success=true;sent++}catch{failed++;logEvent("error",{correlationId:requestId,route,operation:"send",errorCode:"email_provider_failed",metadata:{notification_id:item.notification_id}})}finally{await s.rpc("complete_notification_email",{p_notification_id:item.notification_id,p_success:success})}}const status=failed===0?"succeeded":sent===0?"failed":"partial";await s.rpc("record_job_result",{p_job_name:"notification_email",p_status:status,p_attempted:data?.length??0,p_succeeded:sent,p_error_code:failed?"email_provider_failed":null,p_correlation_id:requestId,p_started_at:startedAt});if(failed)await s.rpc("record_operational_failure",{p_correlation_id:requestId,p_route:route,p_operation:"send",p_error_code:"email_provider_failed",p_safe_metadata:{failed_count:failed}});logEvent(failed?"warn":"info",{correlationId:requestId,route,operation:"complete",metadata:{claimed:data?.length??0,sent,failed}});return respond({claimed:data?.length??0,sent,failed})}

// Cloudflare invokes POST through the custom scheduled handler. Keep GET
// available for authenticated operational replays from a trusted runner.
export const GET = POST;
