import Link from "next/link";
import { notFound } from "next/navigation";
import { EvidenceDownloadButton, EvidenceUploader } from "@/components/evidence-uploader";
import { CaseInvitationForm } from "@/components/case-invitation-form";
import { PageHeader } from "@/components/community-shell";
import { StatusBadge } from "@/components/record-cards";
import { requireCommunityUser } from "@/lib/community";
import { createClient } from "@/lib/supabase/server";
import { flagReportAction, recordResponseAction, setOfficialStatusAction, setReportStatusAction, submitModerationReviewAction } from "./actions";

const input = "min-h-11 rounded-lg border border-[#aaa59e] bg-white px-3";
const officialLabels: Record<string,string> = {received:"Recebida",under_analysis:"Em análise",forwarded:"Encaminhada",in_execution:"Em execução",awaiting_third_party:"Aguardando terceiro",service_reported_completed:"Serviço informado como concluído",closed_by_management:"Encerrada pela administração"};

export default async function ReportDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requireCommunityUser();
  const { id } = await params; const supabase = await createClient();
  const [{ data: report }, { data: author }, { data: responses }, { data: commitments }, { data: attachments }, { data: official }, { data: representations }, { data: moderationActions }] = await Promise.all([
    supabase.from("reports").select("id,protocol,issue_id,report_type_id,title,description,occurred_at,recorded_at,urgency,scope,sensitivity,status_definition_id,report_types(name),report_status_definitions(slug,label)").eq("id",id).maybeSingle(),
    supabase.rpc("current_user_is_report_author",{p_report_id:id}),
    supabase.from("responses").select("id,response_type,attributed_to,channel,occurred_at,body,action_informed,created_at").eq("report_id",id).is("hidden_at",null).order("occurred_at"),
    supabase.from("commitments").select("id,source_label,assigned_to,description,assumed_at,current_due_at,status,fulfilled_at").eq("report_id",id).order("created_at"),
    supabase.from("attachments").select("id,storage_path,original_filename,mime_type,size_bytes,sha256,description").eq("report_id",id).eq("upload_status","ready").is("hidden_at",null).order("created_at"),
    supabase.from("official_status_current").select("status,note,recorded_at").eq("report_id",id).maybeSingle(),
    supabase.from("official_representations").select("id,role_type,organization").eq("status","active").lte("starts_at",new Date().toISOString()).or(`ends_at.is.null,ends_at.gt.${new Date().toISOString()}`),
    supabase.from("moderation_actions").select("id,action_type,reason,created_at,reverted_at").eq("target_type","report").eq("target_id",id).is("reverted_at",null).order("created_at",{ascending:false}),
  ]);
  if (!report) notFound();
  const { data: statuses } = await supabase.from("report_status_definitions").select("slug,label").eq("report_type_id",report.report_type_id).order("sort_order");
  return <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6">
    <PageHeader eyebrow={report.protocol} title={report.title} description="O relato original permanece preservado; respostas, evidências, estados e compromissos entram na trilha." />
    <div className="mt-4 flex flex-wrap gap-3"><StatusBadge value={report.urgency}/><Link href={`/problemas/${report.issue_id}`} className="font-semibold text-forest underline">Ver problema coletivo</Link></div>
    <section className="mt-6 rounded-xl border bg-white p-5"><p className="whitespace-pre-wrap">{report.description}</p><p className="mt-4 text-sm text-[#666861]">Registrado em {new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(report.recorded_at))}</p>{official&&<div className="mt-4 rounded-lg bg-[#e8f3f7] p-3"><b>Status operacional oficial: {officialLabels[official.status]??official.status}</b>{official.note&&<p>{official.note}</p>}</div>}</section>
    {author&&<form action={setReportStatusAction} className="mt-5 grid gap-3 rounded-xl border bg-white p-5 sm:grid-cols-[1fr_2fr_auto]"><input type="hidden" name="report_id" value={id}/><select className={input} name="status_slug" defaultValue={report.report_status_definitions?.[0]?.slug}>{statuses?.map(status=><option key={status.slug} value={status.slug}>{status.label}</option>)}</select><input className={input} name="reason" required minLength={3} placeholder="Motivo da atualização"/><button className="rounded-lg bg-forest px-4 font-bold text-white">Atualizar meu status</button></form>}
    <section className="mt-8"><h2 className="text-2xl font-bold">Retornos e manifestações</h2><div className="mt-4 space-y-3">{responses?.map(response=><article key={response.id} className="rounded-xl border bg-white p-5"><b>{response.response_type==="official"?"Resposta oficial publicada na plataforma":response.response_type==="party_statement"?"Manifestação de parte citada":"Retorno externo registrado pelo usuário"}</b>{response.response_type==="external_recorded"&&<p className="text-xs text-[#666861]">Autoria externa não verificada diretamente pela plataforma.</p>}<p className="mt-3 whitespace-pre-wrap">{response.body}</p>{response.attributed_to&&<p className="mt-2 text-sm">Atribuído a: {response.attributed_to} · {response.channel}</p>}</article>)}</div></section>
    {author&&<form action={recordResponseAction} className="mt-5 grid gap-3 rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Registrar retorno externo</h2><input type="hidden" name="report_id" value={id}/><input type="hidden" name="response_type" value="external_recorded"/><div className="grid gap-3 sm:grid-cols-2"><input className={input} name="attributed_to" required placeholder="Pessoa ou organização atribuída"/><input className={input} name="channel" required placeholder="Canal (e-mail, mensagem, reunião…)"/></div><input className={input} type="datetime-local" name="occurred_at" required/><textarea className="min-h-28 rounded-lg border p-3" name="body" required minLength={5} placeholder="Conteúdo ou resumo fiel"/><input className={input} name="action_informed" placeholder="Providência informada (opcional)"/><details><summary className="cursor-pointer font-semibold">Adicionar compromisso/prazo</summary><div className="mt-3 grid gap-3 sm:grid-cols-3"><input className={input} name="commitment_description" placeholder="Compromisso"/><input className={input} name="commitment_assigned_to" placeholder="Atribuído a"/><input className={input} type="datetime-local" name="commitment_due_at"/></div></details><button className="min-h-11 rounded-lg bg-brick px-4 font-bold text-white">Registrar retorno atribuído</button></form>}
    {representations?.map(rep=><div key={rep.id} className="mt-5 grid gap-5 lg:grid-cols-2"><form action={recordResponseAction} className="grid gap-3 rounded-xl border bg-white p-5"><h2 className="font-bold">Publicar resposta oficial · {rep.organization??rep.role_type}</h2><input type="hidden" name="report_id" value={id}/><input type="hidden" name="response_type" value="official"/><input type="hidden" name="official_representation_id" value={rep.id}/><input className={input} type="datetime-local" name="occurred_at" required/><textarea className="min-h-28 rounded-lg border p-3" name="body" required/><input className={input} name="action_informed" placeholder="Providência informada"/><button className="rounded-lg bg-forest px-4 py-3 font-bold text-white">Publicar resposta oficial</button></form><form action={setOfficialStatusAction} className="grid gap-3 rounded-xl border bg-white p-5"><h2 className="font-bold">Atualizar status operacional oficial</h2><input type="hidden" name="report_id" value={id}/><input type="hidden" name="representation_id" value={rep.id}/><select className={input} name="status">{Object.entries(officialLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><textarea className="min-h-20 rounded-lg border p-3" name="note" placeholder="Nota opcional"/><button className="rounded-lg bg-forest px-4 py-3 font-bold text-white">Registrar status oficial</button></form></div>)}
    <section className="mt-8"><h2 className="text-2xl font-bold">Compromissos</h2><div className="mt-4 grid gap-3">{commitments?.map(commitment=><article key={commitment.id} className="rounded-xl border bg-white p-5"><b>{commitment.description}</b><p className="mt-1 text-sm">{commitment.status} · prazo {commitment.current_due_at?new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium"}).format(new Date(commitment.current_due_at)):"não informado"}</p></article>)}</div></section>
    <section className="mt-8"><h2 className="text-2xl font-bold">Evidências privadas</h2><div className="my-4 grid gap-3">{attachments?.map(file=><article key={file.id} className="rounded-xl border bg-white p-4"><b>{file.original_filename}</b><p className="break-all text-xs">SHA-256 {file.sha256}</p><EvidenceDownloadButton path={file.storage_path} filename={file.original_filename}/></article>)}</div><EvidenceUploader reportId={id}/></section>
    {author&&<div className="mt-8"><CaseInvitationForm reportId={id}/></div>}
    {author&&moderationActions?.map(action=><form key={action.id} action={submitModerationReviewAction} className="mt-5 grid gap-3 rounded-xl border border-gold bg-[#fffaf0] p-5"><b>Ação de moderação: {action.action_type}</b><p>{action.reason}</p><input type="hidden" name="report_id" value={id}/><input type="hidden" name="action_id" value={action.id}/><textarea name="rationale" required minLength={10} className="min-h-24 rounded-lg border p-3" placeholder="Explique por que solicita revisão"/><button className="rounded-lg border border-brick p-3 font-bold text-brick">Solicitar revisão</button></form>)}
    <form action={flagReportAction} className="mt-8 grid gap-3 rounded-xl border border-[#e2c7c2] bg-white p-5"><h2 className="text-lg font-bold">Sinalizar conteúdo</h2><input type="hidden" name="report_id" value={id}/><select name="reason" className={input}><option value="personal_data">Dados pessoais expostos</option><option value="harassment">Ofensa ou assédio</option><option value="potentially_inappropriate_allegation">Alegação potencialmente inadequada</option><option value="spam">Spam</option><option value="off_purpose">Fora do propósito</option><option value="other">Outro</option></select><textarea name="details" className="min-h-20 rounded-lg border p-3" placeholder="Contexto opcional"/><button className="rounded-lg border border-danger p-3 font-bold text-danger">Enviar à moderação</button></form>
  </main>;
}
